### ISSUE TITLE
Assertion Error on line 298

### ISSUE THREAD

**Issue by webmaharaj** [xwp/wp-widget-customizer#64] opened 2013-12-13 04:12 UTC
Hello,

The Plugin is showing following warning when we load customzer and displaying everything fine.

Warning: assert() [function.assert]: Assertion failed in wp-content/plugins/wp-widget-customizer-new-widget-addition/widget-customizer.php on line 298

It's showing same for master file too.

thanks

**Comment by westonruter** [comment] 2013-12-13 05:21
@webmaharaj thanks a lot for this report. It seems to be a duplicate of the previously-captured issue #48. Can you confirm that you had changed active plugins or themes and so the widgets available changed?

**Closed as completed** 2013-12-13 07:51 UTC
Labels: duplicate

**Comment by westonruter** [comment] 2013-12-13 07:54
@webmaharaj I just released v0.9.6 which includes the fix.

**Comment by webmaharaj** [comment] 2013-12-13 12:03
Hello,

It's all super cool now. How about integrating new widget selection style in to the master? That's really wonderful than the traditional drop down add widget option :)

thanks.

**Comment by westonruter** [comment] 2013-12-13 16:33
We're working on it :-)

**Comment by westonruter** [comment] 2013-12-22 08:34
@webmaharaj just released v0.11 which includes the new panel for browsing and selecting an available widget to add: http://wordpress.org/plugins/widget-customizer/
