### ISSUE TITLE
New custom menu doesn't appear until pressing save/update

### ISSUE THREAD

**Issue by bobbravo2** [xwp/wp-widget-customizer#44] opened 2013-10-26 03:04 UTC
Title sums it up - using the #3 "add new custom menu", doesn't add it to the view until you press save (or update, soon).

**Comment by westonruter** [comment] 2013-10-26 07:43
This should be resolved by #37. The problem is not all widgets can be submitted right when they are added. For example, the RSS widget will show you an error if it gets saved without a URL provided. For the custom menu widget, I believe it is coded to not render anything if no menu is supplied, and since the widget form is not submitted right when it is added, then the widget instance remains empty until they press save/update.

**Closed as completed** 2013-12-09 07:14 UTC
Labels: duplicate
